import {
  Entity,
  PrimaryColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';

/**
 * Passkey credential entity
 * Stores the WebAuthn credential info bound by the user, used for passwordless login and two-factor authentication
 */
@Entity('passkey_credentials')
export class PasskeyCredential {
  /**
   * Unique credential identifier
   * UUID format
   */
  @PrimaryColumn()
  guid: string;

  /**
   * Unique identifier of the owning user
   * References the guid field of the users table
   */
  @Column()
  @Index()
  userGuid: string;

  /**
   * WebAuthn credential ID
   * base64url-encoded, generated by the authenticator, globally unique
   * Used at login to look up the user, enabling passwordless login
   */
  @Column({ type: 'varchar', unique: true })
  credentialId: string;

  /**
   * Credential public key
   * base64url-encoded, used to verify authenticator signatures
   */
  @Column({ type: 'varchar' })
  credentialPublicKey: string;

  /**
   * Signature counter
   * Incremented by the authenticator on each authentication; the server verifies it increases to detect credential cloning
   */
  @Column({ default: 0 })
  counter: number;

  /**
   * Transports
   * JSON array, e.g. ["internal", "hybrid"]
   * The browser uses this to choose how to invoke the authenticator
   */
  @Column({ type: 'varchar', nullable: true })
  transports: string | null;

  /**
   * Device type
   * 'singleDevice' - single-device credential (e.g. security key)
   * 'multiDevice' - multi-device credential (e.g. Touch ID, Windows Hello; supports cloud sync)
   */
  @Column({ type: 'varchar', nullable: true })
  deviceType: string;

  /**
   * Whether it is backed up
   * Multi-device credentials are usually backed up to the cloud (iCloud/Google)
   */
  @Column({ default: false })
  backedUp: boolean;

  /**
   * User-defined credential name
   * Used to tell credentials apart in the admin UI
   */
  @Column({ type: 'varchar', nullable: true })
  name: string | null;

  /**
   * Creation time
   */
  @CreateDateColumn()
  createdAt: Date;

  /**
   * Update time
   */
  @UpdateDateColumn()
  updatedAt: Date;
}
