import {
  Entity,
  PrimaryColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';

/**
 * OIDC authorization state enum
 */
export enum OidcAuthStatus {
  PENDING = 'pending', // Waiting for user authorization
  AUTHORIZED = 'authorized', // Authorized
  CONSUMED = 'consumed', // Consumed (token has been retrieved by the client)
  EXPIRED = 'expired', // Expired
  CANCELLED = 'cancelled', // Cancelled
}

/**
 * OIDC authorization state entity
 * Manages the temporary state of the OIDC authorization flow
 */
import { OidcProviderType } from './oidc-provider.entity';

@Entity('oidc_auth_states')
export class OidcAuthState {
  /**
   * Unique authorization state identifier
   * UUID format, uniquely identifies an authorization state
   */
  @PrimaryColumn()
  guid: string;

  /**
   * Authorization code
   * Authorization code used for polling queries
   */
  @Column()
  @Index()
  code: string;

  /**
   * OIDC provider identifier
   * e.g. oidc/google
   */
  @Column()
  @Index()
  op: string;

  @Column({
    type: 'text',
    default: OidcProviderType.OIDC,
  })
  providerType: OidcProviderType;

  /**
   * device ID
   * Device identifier of the RustDesk client (client-only field)
   */
  @Column({ nullable: true })
  deviceId: string;

  /**
   * Device UUID
   * Unique identifier of the device (client-only field)
   */
  @Column({ nullable: true })
  deviceUuid: string;

  /**
   * Device info
   * Detailed device information in JSON format
   */
  @Column({ type: 'text', nullable: true })
  deviceInfo: string;

  /**
   * Redirect URI
   * OIDC callback address
   */
  @Column({ type: 'text', nullable: true })
  redirectUri: string;

  /**
   * OIDC state parameter
   * Used to prevent CSRF attacks
   */
  @Column({ type: 'text', nullable: true })
  state: string;

  /**
   * Authorization state
   * pending - waiting for authorization
   * authorized - authorized
   * expired - expired
   * cancelled - cancelled
   */
  @Column({
    type: 'text',
    default: OidcAuthStatus.PENDING,
  })
  status: OidcAuthStatus;

  /**
   * Unique user identifier
   * User associated after successful authorization
   */
  @Column({ nullable: true })
  userGuid: string;

  /**
   * Access token
   * JWT token generated by the system
   */
  @Column({ nullable: true })
  accessToken: string;

  /**
   * PKCE code verifier
   * Used for Authorization Code Flow + PKCE security hardening
   */
  @Column({ type: 'text', nullable: true })
  codeVerifier: string;

  /**
   * OIDC nonce
   * Used to prevent replay attacks and validate the ID Token
   */
  @Column({ type: 'text', nullable: true })
  nonce: string | null;

  /**
   * Frontend redirect URL
   * For Web frontend login, the frontend address to redirect to after successful authentication
   */
  @Column({ type: 'text', nullable: true })
  frontendRedirectUrl: string | null;

  /**
   * Expiration time
   * Expiration time of the authorization code (default 3 minutes)
   */
  @Column({ type: 'datetime' })
  expiresAt: Date;

  /**
   * Creation time
   */
  @CreateDateColumn()
  createdAt: Date;

  /**
   * Update time
   */
  @UpdateDateColumn()
  updatedAt: Date;
}
